[package]
name = "gen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
bindgen = { version = "0.70.1", default-features = false }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
